# Site Settings
title: RignonNoel
url: 'http://rignonnoel.com'
baseurl: '/' #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
style: styles-5
#style: styles-6


#Profile information
name: Noël Rignon
tagline: Full Stack Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: "I had the chance to develop a wide network and to enhance my personal and technical skills through different positions of supervision and management in companies of various sizes. Today, I am very comfortable to be part of major projects where I can give free rein to my multidisciplinary skills in risk analysis, needs analysis, architecture, design and even in team supervision."
summary_2: "I like to evolve in agile environments with a great awareness of the quality of products developed and continuous improvement initiatives and I really like to integrate these concepts in young companies that only have a limited time and narrow skills. I am looking for innovative backgrounds and offering myself many personal challenges to surpass myself."
summary_3: "You have a project in free software for a non-profit organization ?<br/> Feel free to contact me, it will be a pleasure to help you!"

#sidebar links
sponsor_link: True
email: rignon.noel@gmail.com
phone: (514) 980-3840
website: rignonnoel.com #do not add http://
linkedin: rignonnoel
github: RignonNoel
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
