# Site Settings
title: My Resume
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Noël Rignon
tagline: Développeur Full Stack
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: "J'ai eu la chance de développer un large réseau et de faire valoriser mes compétences personnelles et techniques au travers de différents postes de supervision et de direction dans des entreprises de taille variées. Je suis aujourd'hui très à l'aise dans le fait de m'engager dans des projets d'envergure ou je peux donner libre cours à mes compétences pluridisciplinaires en analyse de risque, en analyse de besoin, en architecture, en conception et même en supervision d'équipe.<br/><br/>
J'aime évoluer dans des milieux agiles ayant une grande conscientisation quant à la qualité des produits développés et aux démarches d'amélioration continue et je me plais énormément à intégrer ces concepts dans des entreprises jeunes qui ne bénéficient que d'une marge de temps et de compétences étroite. Je cherche des milieux innovant et m'offrant des défis personnels nombreux pour me surpasser."

#sidebar links
email: rignon.noel@gmail.com
phone: (514) 980-3840
website: rignonnoel.com #do not add http://
linkedin: rignonnoel
github: RignonNoel
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
